name: Manual Build (Bun + Rust + WASM)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup wasm-pack
        run: |
          cargo install wasm-pack --locked

      - name: Build WASM
        working-directory: wasm
        run: |
          echo "Building WASM using wasm-pack..."
          sh build.sh

      - name: Write environment file
        run: |
          echo "${{ secrets.ENV_CONTENT }}" > .env
          echo ".env file created with secret content"

      - name: Write cookie file
        run: |
          echo "${{ secrets.COOKIE }}" > cookie.json

      - name: Install dependencies
        run: bun install

      - name: Run index.ts
        run: bun index.ts

      - name: Commit error.log if failed
        if: failure() || cancelled()
        run: |
          echo "Committing error.log due to failure or cancel..."
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add error.log || true
          git commit -m "🧩 Build failed — upload error.log [skip ci]" || true
          git push origin HEAD:${{ github.ref_name }} || true